# Generated by Django 6.0.7 on 2026-08-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Prompt used to generate the post image with OpenAI'),
        ),
    ]
