# Generated by Django 6.0.7 on 2026-08-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_video_post_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook_post_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_media_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
