# Generated by Django 6.0.7 on 2026-08-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='latest_invoice_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='latest_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='latest_payment_currency',
            field=models.CharField(blank=True, default='usd', max_length=10),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='latest_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='latest_payment_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='latest_receipt_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('past_due', 'Past Due')], default='active', max_length=20),
        ),
    ]
