"""
Django settings for social_media_platform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (next to manage.py)
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]

# Trusted origins for CSRF (required when using Cloudflare Tunnel / HTTPS proxies)
_default_csrf = 'http://localhost:8000,http://127.0.0.1:8000'
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', _default_csrf).split(',')
    if origin.strip()
]

# Cloudflare / reverse proxy terminates SSL; trust X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_FAILURE_VIEW = 'posts.views.csrf_failure'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'subscriptions',
    'posts.apps.PostsConfig',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'social_media_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'social_media_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Set SQLITE_MIGRATE=1 to dump from the local SQLite file (data migration helper)
if os.getenv('SQLITE_MIGRATE', '').strip().lower() in {'1', 'true', 'yes', 'on'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'social_media_platform'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Kolkata')


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Upload limits (bytes) — aligned with form validation
DATA_UPLOAD_MAX_MEMORY_SIZE = 55 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 55 * 1024 * 1024

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'subscriptions:plans'
LOGOUT_REDIRECT_URL = 'core:home'

# Keep session on OAuth return (top-level redirect from Facebook)
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True

# Windows Application Control may block Pillow DLLs; ImageField still works for uploads
SILENCED_SYSTEM_CHECKS = ['fields.E210']

# Email
_email_user = (os.getenv('EMAIL_HOST_USER') or '').strip()
_email_pass = (os.getenv('EMAIL_HOST_PASSWORD') or '').strip()
_email_backend = (os.getenv('EMAIL_BACKEND') or '').strip()
if _email_backend:
    EMAIL_BACKEND = _email_backend
elif _email_user and _email_pass:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = _email_user
EMAIL_HOST_PASSWORD = _email_pass
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').strip().lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    f'SocialFlow <{_email_user}>' if _email_user else 'SocialFlow <noreply@socialplatform.local>',
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '30'))

# OpenAI image generation
OPENAI_API_KEY = (os.getenv('OPENAI_API_KEY') or '').strip()
OPENAI_IMAGE_MODEL = (os.getenv('OPENAI_IMAGE_MODEL') or 'gpt-image-1').strip()
# Landscape social-feed size (shorter than square 1024x1024)
OPENAI_IMAGE_SIZE = (os.getenv('OPENAI_IMAGE_SIZE') or '1536x1024').strip()
OPENAI_IMAGE_QUALITY = (os.getenv('OPENAI_IMAGE_QUALITY') or 'medium').strip()
# True = use 3 bundled sample images (no OpenAI tokens). False = real OpenAI generation.
USE_STATIC_AI_IMAGES = os.getenv('USE_STATIC_AI_IMAGES', 'False').strip().lower() in {
    '1', 'true', 'yes', 'on',
}

# Meta (Facebook Page OAuth + publish)
META_APP_ID = (os.getenv('META_APP_ID') or '').strip()
META_APP_SECRET = (os.getenv('META_APP_SECRET') or '').strip()
META_GRAPH_VERSION = (os.getenv('META_GRAPH_VERSION') or 'v21.0').strip()
# Instagram API with Instagram Login (separate from Facebook)
INSTAGRAM_APP_ID = (os.getenv('INSTAGRAM_APP_ID') or '').strip()
INSTAGRAM_APP_SECRET = (os.getenv('INSTAGRAM_APP_SECRET') or '').strip()
INSTAGRAM_GRAPH_VERSION = (os.getenv('INSTAGRAM_GRAPH_VERSION') or META_GRAPH_VERSION or 'v21.0').strip()
# Public HTTPS origin for Instagram image_url (e.g. Cloudflare tunnel)
PUBLIC_BASE_URL = (os.getenv('PUBLIC_BASE_URL') or '').strip().rstrip('/')
# Direct Graph API credentials (testing / shared Page token — skips OAuth)
META_PAGE_ID = (os.getenv('META_PAGE_ID') or '').strip()
META_PAGE_ACCESS_TOKEN = (os.getenv('META_PAGE_ACCESS_TOKEN') or '').strip()
META_INSTAGRAM_BUSINESS_ACCOUNT_ID = (os.getenv('META_INSTAGRAM_BUSINESS_ACCOUNT_ID') or '').strip()
META_PAGE_NAME = (os.getenv('META_PAGE_NAME') or 'Facebook Page').strip()

